# Example configuration for evaluating a pretrained backbone with different heads
# 
# Usage:
# 1. Train a model first (e.g., SupCon with MobileNet Small on CIFAR-10)
# 2. Set evaluation.enabled: true and evaluation.checkpoint_path to your checkpoint
# 3. Choose head_type: "classification" or "detection"
# 4. Run evaluation

model: mobilenet_v3_small
database: databases/cifar10
device: cuda:0
seed: 42

# Evaluation configuration
evaluation:
  enabled: true
  checkpoint_path: outputs/mobilenet_small_supcon_mperclass_cifar10_v3/mobilenet_small_supcon_mperclass_cifar10_v3_cycle1.pt
  head_type: classification  # Options: "classification" or "detection"
  num_anchors: 9  # For detection head only
  hidden_dim: 256  # For detection head only

# These settings are used for evaluation
hyperparameters:
  batch_size: 256
  lr: 0.01  # Learning rate for training the head (backbone stays frozen)
  epochs: 20  # Number of epochs to train the head
  momentum: 0.9
  num_workers: 12
  val_split: 0.0  # Use test set if available, otherwise split train
  image_size: 32
  projection_dim: 128
  projection_hidden_dim: 2048
  projection_use_bn: true

# Note: The following are not used during evaluation but kept for compatibility
optimizer: sgd
loss_function: cross_entropy
weight_decay: 0.0001
save_model: false
freeze_backbone: true  # Always true during evaluation


