model: mobilenet_v3_small
database: coco
device: cuda:1
seed: 42

# These are mostly ignored in evaluation mode, but kept for completeness.
optimizer: sgd
loss_function: cross_entropy
weight_decay: 0.0001

mixed_precision: false
save_model: true
save_model_path: output_object_detection/mobilenet_supcon_coco_eval
report_filename: output_object_detection/mobilenet_supcon_coco_eval/detection_metrics.csv

evaluation:
  enabled: true
  head_type: detection
  # Point this to your SupCon MobileNet checkpoint (cycle checkpoint works great).
  checkpoint_path: outputs/mobilenet_small_supcon_mperclass_cifar10_fixlr/mobilenet_small_supcon_mperclass_cifar10_fixlr_cycle10.pt
  num_anchors: 50           # number of slot predictions per image
  hidden_dim: 256
  save_predictions: true
  predictions_path: output_object_detection/mobilenet_supcon_coco_eval/coco_predictions.json
  nms_threshold: 0.5
  map_iou_thresholds: null  # null -> COCO default mAP@[0.5:0.95]

hyperparameters:
  # Detection head training (backbone is frozen)
  batch_size: 16
  lr: 0.001  # Lower LR for better stability with domain transfer
  epochs: 50  # More epochs needed for 80 classes + domain transfer
  momentum: 0.9
  num_workers: 8
  image_size: 224

  # Keep these aligned with the checkpoint config (used to build a compatible model skeleton)
  projection_dim: 128
  projection_hidden_dim: 2048
  projection_use_bn: true

  # Detection-loss + evaluation knobs
  bbox_loss_weight: 1.0  # Increase bbox weight to balance with high cls loss
  match_iou_threshold: 0.3
  iou_threshold: 0.5
  score_threshold: 0.01  # Lower threshold for 80 classes (random chance = 1/80 = 0.0125)
  nms_iou_threshold: 0.5

  # CodeCarbon
  track_emissions: true

  # Optional: limit dataset size for a fast smoke test
  max_train_images: 500
  max_val_images: 200

