model: resnet18
database: coco
device: cuda:1
seed: 42
optimizer: sgd
loss_function: supcon
weight_decay: 0.0001

scheduler:
  type: cosine_annealing
  params:
    eta_min: 0.0
    t_max_strategy: per_batch
    warmup_epochs: 10
  step_on_batch: true

gradient_clip_norm: 1.0
mixed_precision: true
save_model: true
save_model_path: outputs/resnet18_supcon_coco_pretrain_cuda1
checkpoint_path: null
freeze_backbone: false

early_stopping:
  enabled: false
  patience: 3
  metric: val_loss
  mode: min

simclr_schedule:
  enabled: true
  # Multi-cycle: pretrain → evaluate (frozen backbone) → continue pretrain → evaluate...
  # Each cycle evaluates backbone quality with detection head to learn spatial features
  cycles: 3
  pretrain_epochs: 100
  finetune_epochs: 40
  pretrain_loss: supcon
  finetune_loss: cross_entropy  # Not used for detection, but kept for compatibility
  finetune_head_type: detection  # Use detection head instead of classification
  finetune_lr: 0.001  # Lower LR for detection head training
  finetune_optimizer: adamw  # Better for detection
  finetune_weight_decay: 0.0001
  freeze_backbone: true  # Freeze backbone during detection evaluation
  optimizer_reset: true
  use_reference_transforms: true
  linear_subset_per_class: null
  linear_subset_seed: 42

evaluation:
  enabled: false  # Not used directly, but config needed for detection head params
  head_type: detection
  num_anchors: 100
  hidden_dim: 512
  use_bn: true
  dropout: 0.1
  nms_threshold: 0.5
  map_iou_thresholds: null
  filter_coco_to_cifar100: false  # Use full 80 COCO classes

report_filename: resnet18_supcon_coco_pretrain_cuda1/resnet18_supcon_coco_pretrain_cuda1.csv

hyperparameters:
  # For COCO with 80 classes - using standard sampler (no m-per-class needed for ResNet18)
  batch_size: 256  # Standard batch size
  lr: 0.5  # Higher LR for contrastive learning
  epochs: 300  # NOTE: Ignored when simclr_schedule.enabled=true (uses pretrain_epochs per cycle instead)
  momentum: 0.9
  temperature: 0.25
  num_workers: 12
  val_split: 0.0  # COCO has separate val set
  image_size: 224  # COCO uses 224x224
  projection_dim: 128
  projection_hidden_dim: 2048
  projection_use_bn: true
  use_gaussian_blur: true
  simclr_reference_transforms: true
  linear_subset_per_class: null
  linear_subset_seed: 42
  # No m-per-class sampler needed for ResNet18
  use_m_per_class_sampler: false
  
  # Detection-specific hyperparameters (used in finetune phase)
  bbox_loss_weight: 30.0
  bbox_loss_max_weight: 50.0
  bbox_loss_warmup_epochs: 10
  match_iou_threshold: 0.1
  iou_threshold: 0.5
  score_threshold: 0.01
  nms_iou_threshold: 0.5
  gradient_clip_norm: 1.0
  checkpoint_interval: 50