model: resnet18
database: coco
device: cuda:1
seed: 42

# These are mostly ignored in evaluation mode, but kept for completeness.
optimizer: adamw  # Better for detection heads
loss_function: cross_entropy
weight_decay: 0.0001

scheduler:
  type: warmup_cosine
  params:
    eta_min: 0.0001  # Don't decay to zero
    t_max: 100  # Will be auto-adjusted to epochs in code
    warmup_epochs: 5  # 5 epochs warmup (converted to warmup_steps in code)
    warmup_start_factor: 0.1

mixed_precision: false
save_model: true
save_model_path: output_object_detection/resnet18_supcon_coco_eval_filtered
report_filename: output_object_detection/resnet18_supcon_coco_eval_filtered/detection_metrics.csv

evaluation:
  enabled: true
  head_type: detection
  # ResNet18 SupCon trained on CIFAR-100 (100 classes) - should transfer better than CIFAR-10
  checkpoint_path: outputs_old2/resnet18_supcon_full_cifar100_v3/resnet18_supcon_full_cifar100_v3_cycle10.pt
  num_anchors: 100  # Increased from 50 to 100 for better coverage
  hidden_dim: 512  # Increased capacity
  use_bn: true  # Batch normalization for better training
  dropout: 0.1  # Dropout for regularization
  save_predictions: true
  predictions_path: output_object_detection/resnet18_supcon_coco_eval_filtered/coco_predictions.json
  nms_threshold: 0.5
  map_iou_thresholds: null  # null -> COCO default mAP@[0.5:0.95]
  filter_coco_to_cifar100: true  # NEW: Filter COCO to only classes that match CIFAR-100

hyperparameters:
  # Detection head training (backbone is frozen)
  batch_size: 32  # Increased batch size for better stability
  lr: 0.001  # Lower LR for better stability with domain transfer
  epochs: 100  # More epochs needed for domain transfer
  momentum: 0.9
  num_workers: 8
  image_size: 224
  gradient_clip_norm: 1.0  # Prevent exploding gradients

  # Keep these aligned with the checkpoint config (used to build a compatible model skeleton)
  # ResNet18 typically uses these projection settings
  projection_dim: 128
  projection_hidden_dim: 2048
  projection_use_bn: true

  # Detection-loss + evaluation knobs
  bbox_loss_weight: 30.0  # Increased further to emphasize bbox regression
  bbox_loss_max_weight: 50.0  # Max weight during warmup (first 10 epochs)
  bbox_loss_warmup_epochs: 10  # Warmup epochs for bbox loss
  match_iou_threshold: 0.1  # Lower threshold for easier matching (was 0.3)
  iou_threshold: 0.5
  score_threshold: 0.01  # Lower threshold (will be adjusted for filtered classes)
  nms_iou_threshold: 0.5

  # CodeCarbon
  track_emissions: true

  # Optional: limit dataset size for a fast smoke test
  max_train_images: 500
  max_val_images: 200
