# Example config for evaluating pretrained MobileNet Small SupCon with Pascal VOC object detection
# 
# Prerequisites:
# 1. Download Pascal VOC dataset first using "Download databases" menu
# 2. Train your feature space model (e.g., SupCon on CIFAR-10)
# 3. Update checkpoint_path to point to your trained model
# 4. Run this config to fine-tune detection head on Pascal VOC

model: mobilenet_v3_small
database: databases/voc  # Pascal VOC object detection dataset
device: cuda:0  # Adjust based on available GPU
seed: 42

# Evaluation configuration
evaluation:
  enabled: true
  checkpoint_path: outputs_old2/mobilenet_small_supcon_mperclass_cifar10_v3/mobilenet_small_supcon_mperclass_cifar10_v3_cycle10.pt
  head_type: detection
  num_anchors: 9  # 3 scales × 3 aspect ratios
  hidden_dim: 256

# Hyperparameters for training the detection head
hyperparameters:
  batch_size: 16  # Smaller batch for detection
  lr: 0.001  # Lower LR for detection fine-tuning
  epochs: 30
  momentum: 0.9
  num_workers: 8
  val_split: 0.0  # Use VOC val2012 set
  image_size: 224  # Pascal VOC images are larger than CIFAR-10
  projection_dim: 128  # Must match original training
  projection_hidden_dim: 2048  # Must match original training
  projection_use_bn: true  # Must match original training

# These are not used during evaluation but kept for compatibility
optimizer: sgd
loss_function: cross_entropy
weight_decay: 0.0001
save_model: false
freeze_backbone: true  # Always true during evaluation

